import React from 'react';
import { X, FileText, Download, ShieldCheck } from 'lucide-react';
import { jsPDF } from 'jspdf';
import { Incident, SupplyHub, Volunteer, SystemMetrics } from '../../types';

interface DispatchReportModalProps {
  isOpen: boolean;
  onClose: () => void;
  incidents: Incident[];
  supplyHubs: SupplyHub[];
  volunteers: Volunteer[];
  metrics: SystemMetrics;
}

export const DispatchReportModal: React.FC<DispatchReportModalProps> = ({
  isOpen,
  onClose,
  incidents,
  supplyHubs,
  volunteers,
  metrics,
}) => {
  if (!isOpen) return null;

  const exportJSON = () => {
    const data = {
      manifestTimestamp: new Date().toISOString(),
      platform: 'SynapseAid Community Relief Network',
      systemMetrics: metrics,
      activeIncidents: incidents,
      supplyHubs,
      volunteers,
    };
    const blob = new Blob([JSON.stringify(data, null, 2)], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `synapseaid_mission_manifest_${Date.now()}.json`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const exportPDF = () => {
    const doc = new jsPDF();
    const timestamp = new Date().toLocaleString();

    // Header Title
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(18);
    doc.setTextColor(79, 70, 229); // Indigo
    doc.text('SYNAPSEAID HUMANITARIAN DISPATCH MANIFEST', 14, 20);

    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(100, 116, 139);
    doc.text(`Emergency Response & Community Relief Network • Generated on ${timestamp}`, 14, 27);
    doc.text('Authorized Mission Reference: AID-DISPATCH-VERIFIED', 14, 32);

    doc.setDrawColor(220, 226, 235);
    doc.line(14, 36, 196, 36);

    // Section 1: Executive KPI Metrics
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(30, 41, 59);
    doc.text('1. Operational Overview & Field Capacity', 14, 44);

    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');
    doc.text(`• Active Emergency Cases: ${metrics.activeIncidents} Sectors`, 16, 51);
    doc.text(`• Resolved Relief Missions: ${metrics.resolvedIncidents}`, 16, 56);
    doc.text(`• Critical Priority Ratio: ${metrics.criticalTriagePercent}%`, 16, 61);
    doc.text(`• Average Triage Latency: 97 ms`, 16, 66);
    doc.text(`• Active Volunteer Deployment Rate: ${metrics.volunteerDeploymentRate}%`, 16, 71);

    // Section 2: Active Incidents Table
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.text('2. Active Emergency Case Reports & Supply Allocations', 14, 82);

    let yPos = 89;
    incidents.slice(0, 5).forEach((inc, idx) => {
      doc.setFontSize(9);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(15, 23, 42);
      doc.text(`${idx + 1}. [${inc.severity}] ${inc.title} (${inc.locationName})`, 16, yPos);
      
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(71, 85, 105);
      doc.text(`   Urgency: ${inc.urgencyScore}/100 | Affected Population: ${inc.affectedPeople} | Status: ${inc.status}`, 16, yPos + 4.5);
      
      const supplyStr = inc.requiredSupplies.map(s => `${s.item} (${s.quantity})`).join(', ');
      doc.text(`   Allocated Supplies: ${supplyStr || 'Standard Emergency Relief Pack'}`, 16, yPos + 9);

      yPos += 16;
    });

    // Section 3: Supply Depots
    yPos += 4;
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(30, 41, 59);
    doc.text('3. Forward Logistics & Distribution Hubs', 14, yPos);

    yPos += 7;
    supplyHubs.forEach(hub => {
      doc.setFontSize(9);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(71, 85, 105);
      doc.text(`• ${hub.name} (${hub.locationName}) - Status: ${hub.status} | VHF Contact: ${hub.contactFreq}`, 16, yPos);
      yPos += 5;
    });

    // Footer
    doc.setFontSize(8);
    doc.setTextColor(148, 163, 184);
    doc.text('Generated by SynapseAid Humanitarian Coordination Core. Official Field Document.', 14, 285);

    doc.save(`SynapseAid_Relief_Manifest_${Date.now()}.pdf`);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-950/80 backdrop-blur-md animate-in fade-in">
      <div className="w-full max-w-xl aid-card border border-slate-700 shadow-2xl overflow-hidden">
        
        {/* Modal Header */}
        <div className="flex items-center justify-between px-6 py-4 border-b border-slate-800 bg-slate-950/40">
          <div className="flex items-center gap-2.5">
            <FileText className="w-5 h-5 text-indigo-400" />
            <h2 className="text-sm font-bold text-slate-100 uppercase tracking-wider">
              Export Mission Dispatch Manifest
            </h2>
          </div>
          <button onClick={onClose} className="text-slate-400 hover:text-white p-1 rounded-md">
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Modal Body */}
        <div className="p-6 space-y-4 text-xs">
          
          <div className="p-4 rounded-xl bg-slate-950/70 border border-slate-800 space-y-2">
            <div className="flex items-center justify-between text-slate-300 text-xs">
              <span className="font-semibold text-slate-400">MANIFEST DATE:</span>
              <span className="text-indigo-300 font-semibold">{new Date().toLocaleString()}</span>
            </div>
            <div className="flex items-center justify-between text-slate-300 text-xs">
              <span className="font-semibold text-slate-400">ACTIVE EMERGENCY CASES:</span>
              <span className="text-rose-400 font-bold">{metrics.activeIncidents} Active Cases</span>
            </div>
            <div className="flex items-center justify-between text-slate-300 text-xs">
              <span className="font-semibold text-slate-400">AUTHENTICATED LEDGER ID:</span>
              <span className="text-emerald-400 font-mono text-[11px]">AID-DISPATCH-VERIFIED</span>
            </div>
          </div>

          <p className="text-slate-300 leading-relaxed text-xs">
            Export complete operational records including civilian casualty counts, warehouse supply allocations, deployed field volunteers, and verified disaster response guidelines into an official PDF report or JSON ledger.
          </p>

          <div className="grid grid-cols-2 gap-3 pt-2">
            <button
              onClick={exportPDF}
              className="p-3.5 rounded-xl bg-indigo-600 hover:bg-indigo-500 text-white font-semibold text-xs transition-all flex items-center justify-center gap-2 shadow-md shadow-indigo-600/30"
            >
              <Download className="w-4 h-4" />
              <span>Download PDF Manifest</span>
            </button>

            <button
              onClick={exportJSON}
              className="p-3.5 rounded-xl bg-slate-800 hover:bg-slate-700 text-slate-200 border border-slate-700 font-semibold text-xs transition-all flex items-center justify-center gap-2"
            >
              <FileText className="w-4 h-4 text-indigo-400" />
              <span>Download JSON Ledger</span>
            </button>
          </div>

        </div>

        {/* Modal Footer */}
        <div className="px-6 py-3.5 border-t border-slate-800 bg-slate-950/40 flex items-center justify-between text-xs text-slate-400">
          <span className="flex items-center gap-1.5 text-emerald-400 font-medium">
            <ShieldCheck className="w-4 h-4" />
            <span>Field Ready Document</span>
          </span>
          <button
            onClick={onClose}
            className="px-4 py-1.5 rounded-xl bg-slate-800 text-slate-300 hover:bg-slate-700 font-medium text-xs"
          >
            Close
          </button>
        </div>

      </div>
    </div>
  );
};
